# https://github.com/hvr/multi-ghc-travis
sudo: false

env:
 - CABALVER=1.22 GHCVER=7.10.1
 - CABALVER=head GHCVER=head

before_install:
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:/opt/happy/1.19.5/bin:$PATH
 - travis_retry cabal update
 - export PATH=$HOME/.cabal/bin:$PATH

install:
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - cabal install --only-dependencies -f-build-js

script:
 - cabal configure -f-build-js -v2
 - cabal build
 # commented out because Python tests don't want to run
 # - cabal test

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - ghc-7.10.1
    - ghc-head
    - cabal-install-1.22
    - cabal-install-head
    - happy-1.19.5
