language: haskell

ghc:
  - '7.10'
  - '7.8'

install:
 - cabal install happy
 - cabal install --only-dependencies --enable-tests

script:
 - cabal configure --enable-tests -f '''-build-js'''
 - cabal build '--ghc-options=''-fno-warn-dodgy-imports -Werror'''

 # uncomment once Travis's version of Cabal knows about PatternSynonyms
 # - cabal check

 # commented out because Python tests don't want to run
 # - cabal test
