sudo: false

before_install:
 - export PATH=/opt/ghc/7.10.2/bin:/opt/cabal/1.22/bin:/opt/happy/1.19.5/bin:$PATH
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal update
 - mkdir $HOME/.bin
 - ln -s $(which python3.4) $HOME/.bin/python3
 - export PATH=$HOME/.bin:$PATH
 - python3 --version

install:
 - cabal install --dep -f-build-js --enable-tests

script:
 - cabal configure -f-build-js --enable-tests -v2
 - cabal build
 - cabal test

addons:
  apt:
    sources:
    - hvr-ghc
    - deadsnakes
    packages:
    - ghc-7.10.2
    - cabal-install-1.22
    - happy-1.19.5
    - python3.4
